version: '3'
  services:
    green:
      build: .
      image: ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}
      container_name: green
      environment:
        - LANG=ko_KR.UTF-8
      ports:
        - '8082:8080'