version: '3'
  services:
    blue:
      build: .
      image: ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}
      container_name: blue
      environment:
        - LANG=ko_KR.UTF-8
      ports:
        - '8081:8080'