name: build/test

on: # when the workflows should be triggered ?
  pull_request: # Starting Build when pull request is created.
    branches: [ "main", "dev"]
  push: 
    branches: ["dev"]

permissions:
  contents: read

jobs: # defining jobs, executed in this workflows
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # clone repository

      # Caching Gradle
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{  runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 17
      uses: actions/setup-java@v3 # set up the required java version
      with:
        java-version: '17'

    - name: Gradle Authorization
      run: chmod +x gradlew
    - name: Gradle Build Run
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew test